
package com.ws.convenio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConvenioWS", targetNamespace = "http://convenio.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConvenioWS {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerConvenio", targetNamespace = "http://convenio.ws.com/", className = "com.ws.convenio.ObtenerConvenio")
    @ResponseWrapper(localName = "obtenerConvenioResponse", targetNamespace = "http://convenio.ws.com/", className = "com.ws.convenio.ObtenerConvenioResponse")
    @Action(input = "http://convenio.ws.com/ConvenioWS/obtenerConvenioRequest", output = "http://convenio.ws.com/ConvenioWS/obtenerConvenioResponse")
    public List<Object> obtenerConvenio();

}
