
package com.ws.soap.saldo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SaldoWS", targetNamespace = "http://saldo.soap.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SaldoWS {


    /**
     * 
     * @param cliente
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSaldo", targetNamespace = "http://saldo.soap.ws.com/", className = "com.ws.soap.saldo.ObtenerSaldo")
    @ResponseWrapper(localName = "obtenerSaldoResponse", targetNamespace = "http://saldo.soap.ws.com/", className = "com.ws.soap.saldo.ObtenerSaldoResponse")
    @Action(input = "http://saldo.soap.ws.com/SaldoWS/obtenerSaldoRequest", output = "http://saldo.soap.ws.com/SaldoWS/obtenerSaldoResponse")
    public double obtenerSaldo(
        @WebParam(name = "cliente", targetNamespace = "")
        String cliente);

}
