
package com.ws.soap.saldo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaldoWS", targetNamespace = "http://saldo.soap.ws.com/", wsdlLocation = "http://localhost:8080/SaldoWS/SaldoWS?wsdl")
public class SaldoWS_Service
    extends Service
{

    private final static URL SALDOWS_WSDL_LOCATION;
    private final static WebServiceException SALDOWS_EXCEPTION;
    private final static QName SALDOWS_QNAME = new QName("http://saldo.soap.ws.com/", "SaldoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SaldoWS/SaldoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALDOWS_WSDL_LOCATION = url;
        SALDOWS_EXCEPTION = e;
    }

    public SaldoWS_Service() {
        super(__getWsdlLocation(), SALDOWS_QNAME);
    }

    public SaldoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALDOWS_QNAME, features);
    }

    public SaldoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SALDOWS_QNAME);
    }

    public SaldoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALDOWS_QNAME, features);
    }

    public SaldoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaldoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaldoWS
     */
    @WebEndpoint(name = "SaldoWSPort")
    public SaldoWS getSaldoWSPort() {
        return super.getPort(new QName("http://saldo.soap.ws.com/", "SaldoWSPort"), SaldoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaldoWS
     */
    @WebEndpoint(name = "SaldoWSPort")
    public SaldoWS getSaldoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://saldo.soap.ws.com/", "SaldoWSPort"), SaldoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALDOWS_EXCEPTION!= null) {
            throw SALDOWS_EXCEPTION;
        }
        return SALDOWS_WSDL_LOCATION;
    }

}
