
package com.ws.soap.banco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuarioWS", targetNamespace = "http://banco.soap.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioWS {


    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarUsuario", targetNamespace = "http://banco.soap.ws.com/", className = "com.ws.soap.banco.ValidarUsuario")
    @ResponseWrapper(localName = "validarUsuarioResponse", targetNamespace = "http://banco.soap.ws.com/", className = "com.ws.soap.banco.ValidarUsuarioResponse")
    @Action(input = "http://banco.soap.ws.com/UsuarioWS/validarUsuarioRequest", output = "http://banco.soap.ws.com/UsuarioWS/validarUsuarioResponse")
    public boolean validarUsuario(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
